import type { Metadata } from 'next'

import './globals.scss'
import { areaRegular, aeonikBold } from '@/utils/fonts'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${areaRegular.variable} ${aeonikBold.variable}`}>
                {children}
            </body>
        </html>
    )
}
